
export const INGREDIENT_SHOW = "INGREDIENT_SHOW"
export const INGREDIENT_UPDATE = "INGREDIENT_UPDATE"
export const INGREDIENT_CREATE = "INGREDIENT_CREATE"
export const INGREDIENT_DELETE = "INGREDIENT_DELETE"
    