
export const PRODUCTCATEGORY_SHOW = "PRODUCTCATEGORY_SHOW"
export const PRODUCTCATEGORY_UPDATE = "PRODUCTCATEGORY_UPDATE"
export const PRODUCTCATEGORY_CREATE = "PRODUCTCATEGORY_CREATE"
export const PRODUCTCATEGORY_DELETE = "PRODUCTCATEGORY_DELETE"
    